declare namespace MeetingManager {
  /**
   * PUBLIC_INTERFACE
   * Meeting
   * Represents a meeting entity stored in Supabase and used throughout the frontend.
   *
   * Field descriptions and expected Supabase column types:
   * - id: string (uuid) - Primary key (Supabase: uuid, default uuid_generate_v4())
   * - user_id: string (uuid) - Owner user id; references auth.users.id (Supabase: uuid, FK)
   * - title: string - Meeting title (Supabase: text, not null)
   * - description?: string | null - Long description/agenda (Supabase: text, nullable)
   * - location?: string | null - Physical/virtual location (Supabase: text, nullable)
   * - start_time: string - ISO8601 datetime in UTC (Supabase: timestamptz, not null)
   * - end_time: string - ISO8601 datetime in UTC (Supabase: timestamptz, not null)
   * - attendees: string[] - Array of attendee emails (Supabase: text[] default '{}')
   * - notes?: string | null - Follow-up notes or minutes (Supabase: text, nullable)
   * - tags: string[] - Labels for filtering/search (Supabase: text[] default '{}')
   * - reminders: number[] - Reminder offsets in minutes before start_time (Supabase: int[] default '{}')
   * - source?: string | null - Origin e.g. 'manual', 'google', 'outlook' (Supabase: text, nullable)
   * - external_event_id?: string | null - ID from external calendar provider (Supabase: text, nullable, index)
   * - created_at: string - ISO8601 created timestamp (Supabase: timestamptz, default now())
   * - updated_at: string - ISO8601 updated timestamp (Supabase: timestamptz, trigger or app-managed)
   *
   * Notes:
   * - start_time and end_time should be stored as timestamptz in Supabase and handled as ISO strings in the client.
   * - For attendees/tags arrays, ensure Postgres array ops are used when filtering on the backend; frontend treats as string[].
   * - reminders are integer minutes before start_time; e.g., [5, 15, 60].
   */
  // PUBLIC_INTERFACE
  type Meeting = {
    id: string; // uuid
    user_id: string; // uuid (owner)
    title: string;
    description?: string | null;
    location?: string | null;
    start_time: string; // ISO datetime (UTC recommended)
    end_time: string; // ISO datetime (UTC recommended)
    attendees: string[]; // emails
    notes?: string | null;
    tags: string[];
    reminders: number[]; // minutes before start_time
    source?: string | null;
    external_event_id?: string | null;
    created_at: string; // ISO datetime
    updated_at: string; // ISO datetime
  };

  /**
   * PUBLIC_INTERFACE
   * MeetingInsert
   * Shape for creating a new meeting (fields provided by the client).
   * id/created_at/updated_at should be generated by the DB; user_id set by app.
   */
  // PUBLIC_INTERFACE
  type MeetingInsert = {
    user_id: string;
    title: string;
    start_time: string;
    end_time: string;
    description?: string | null;
    location?: string | null;
    attendees?: string[];
    notes?: string | null;
    tags?: string[];
    reminders?: number[];
    source?: string | null;
    external_event_id?: string | null;
  };

  /**
   * PUBLIC_INTERFACE
   * MeetingUpdate
   * Shape for updating an existing meeting; partial fields allowed.
   */
  // PUBLIC_INTERFACE
  type MeetingUpdate = Partial<
    Omit<Meeting, 'id' | 'user_id' | 'created_at' | 'updated_at'>
  > & {
    // allow moving ownership explicitly if needed by an admin flow
    user_id?: string;
  };
}

export {};
